name: Deploy Staging

inputs:
  old_version: 
    required: false
  version:
    required: false
  commit_hash:
    required: false
  repository:
    required: false
  sender: 
    required: false
  status: 
    required: false
  app_name:
    required: false
  CHANNEL:
    required: true
  color: 
    required: false
  workflow: 
    required: false
  commiter: 
    required: false


runs:
  using: "composite"
  steps:
    - name: test    
      shell: bash 
      run: |
        curl -X POST \
        '${{ inputs.CHANNEL }}' \
          -H 'Content-Type: application/json' \
          -d '{
              "cardsV2": [{
                "cardId": "createCardMessage",
                "card": {
                  "header": {
                    "title": "${{inputs.status}} Job",
                    "subtitle": "${{inputs.workflow}}",
                    "imageUrl": "https://www.silainsights.com/wp-content/uploads/2022/12/cropped-Sila-icon-RGB-primary-32x32.png",
                    "imageType": "CIRCLE"
                  },
                  "sections": [
                    {
                      "header": "<font color=\"#000000\"> Details. </font>",
                      "collapsible": true,
                      "uncollapsibleWidgetsCount": 1,
                      "widgets": [
                        {
                          "textParagraph": {
                            "text": "${{inputs.workflow}}: <b>${{inputs.old_version}}</b> to <b>${{inputs.version}}</b> <br> Commit: <i>#${{inputs.commit_hash}}</i> by <i>#${{inputs.commiter}}</i> <br> app: ${{inputs.app_name}}  <br> Status: <font color=\"#${{inputs.color}}\"> ${{inputs.status}} </font>. <br>  repo: ${{inputs.repository}}  <br>  triggerd by <u>${{inputs.sender}}</u> "
                          }
                        }
                      ]
                    }
                  ],
                  "fixedFooter": {
                    "primaryButton": {
                      "text": "Primary Button",
                      "color": {
                        "red": 0,
                        "green": 0.5,
                        "blue": 1,
                        "alpha": 1
                      },
                      "onClick": {
                        "openLink": {
                          "url": "https://github.com/${{inputs.repository}}/actions"
                        }
                      }
                    }
                  }
                }
              }]
            }'
