name: Deploy Staging

inputs:
  old_version: 
    required: false
  version:
    required: false
  commit_hash:
    required: false
  repository:
    required: false
  sender: 
    required: false
  status: 
    required: false
  app_name:
    required: false

runs:
  using: "composite"
  steps:
    - name: test    
      if: ${{inputs.test == 'Success' }}
      shell: bash 
      run: |
      curl --location --request POST '${{ secrets.CHANNEL }}' \
      --header 'Content-Type: application/json' \
      --data-raw '{
        "header": {
          "title": "Card Title",
          "subtitle": "Card Subtitle",
          "imageUrl": "https://developers.google.com/chat/images/quickstart-app-avatar.png",
          "imageType": "CIRCLE"
        },
        "sections": [
          {
            "header": "Section Header",
            "collapsible": true,
            "uncollapsibleWidgetsCount": 1,
            "widgets": [
              {
                "textParagraph": {
                  "text": "upgrading version: ${{inputs.version}} to ${{inputs.old_version}} from commit: #${{inputs.commit_hash}} for app: ${{inputs.app_name}} with status: ${{inputs.status}} repo: ${{inputs.repository}} triggerd by ${{inputs.sender}} "
                }
              }
            ]
          }
        ],
        "fixedFooter": {
          "primaryButton": {
            "text": "Primary Button",
            "color": {
              "red": 0,
              "green": 0.5,
              "blue": 1,
              "alpha": 1
            },
            "onClick": {
              "action": {
                "function": "onClickPrimaryButton"
              }
            }
          },
          "secondaryButton": {
            "text": "Secondary Button",
            "onClick": {
              "action": {
                "function": "onClickSecondaryButton"
              }
            }
          }
        }
      }'

    - name: test    
      if: ${{inputs.test == 'Fail' }}
      shell: bash 
      run: |
      curl --location --request POST '${{ secrets.CHANNEL }}' \
      --header 'Content-Type: application/json' \
      --data-raw '{
        "header": {
          "title": "Card Title",
          "subtitle": "Card Subtitle",
          "imageUrl": "https://developers.google.com/chat/images/quickstart-app-avatar.png",
          "imageType": "CIRCLE"
        },
        "sections": [
          {
            "header": "Section Header",
            "collapsible": true,
            "uncollapsibleWidgetsCount": 1,
            "widgets": [
              {
                "textParagraph": {
                  "text": "upgrading version: ${{inputs.version}} to ${{inputs.old_version}} from commit: #${{inputs.commit_hash}} for app: ${{inputs.app_name}} with status: ${{inputs.status}} repo: ${{inputs.repository}} triggerd by ${{inputs.sender}} "
                }
              }
            ]
          }
        ],
        "fixedFooter": {
          "primaryButton": {
            "text": "Primary Button",
            "color": {
              "red": 0,
              "green": 0.5,
              "blue": 1,
              "alpha": 1
            },
            "onClick": {
              "action": {
                "function": "onClickPrimaryButton"
              }
            }
          },
          "secondaryButton": {
            "text": "Secondary Button",
            "onClick": {
              "action": {
                "function": "onClickSecondaryButton"
              }
            }
          }
        }
      }'
