name: Deploy Staging

inputs:
  test:
    required: false


runs:
  using: "composite"

  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-tags: 'true'
        fetch-depth: '0'
    - name: test      
      run: |
          echo "SHORT_SHA=$(echo ${GITHUB_SHA} | cut -c1-7)"
          echo "old_tag=$(git describe --tags --always $(git rev-list --tags --max-count=1))"
          echo ${{ inputs.test }}  
