name: Deploy Staging

inputs:
  old_version: 
    required: false
  version:
    required: false
  commit_hash:
    required: false
  repository:
    required: false
  sender: 
    required: false
  status: 
    required: false
  app_name:
    required: false
  CHANNEL:
    required: true
runs:
  using: "composite"
  steps:
    - name: test    
      if: ${{inputs.test == 'Success' }}
      shell: bash 
      run: |
        curl --location --request POST '${{ inputs.CHANNEL }}' \
        --header 'Content-Type: application/json' \
        --data-raw '{"text": "upgrading version: ${{inputs.version}} to ${{inputs.old_version}} from commit: #${{inputs.commit_hash}} for app: ${{inputs.app_name}} with status: ${{inputs.status}} repo: ${{inputs.repository}} triggerd by ${{inputs.sender}} "}'
