name: Update AUTHORS
on:
 push:
  branches:
    - 'tes'
jobs:
  updateAuthors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: create pull request
        run: gh pr create -B tes -H main --title 'Merge branch_to_merge into base_branch "${{ github.sha }}"' --body 'Created by Github action'
        env:
            GITHUB_TOKEN: ${{ secrets.PAT }}

