name: Update AUTHORS
on:
  workflow_dispatch:
  
jobs:
  updateAuthors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Make changes to pull request
        run: date +%s > report.txt
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.PAT }}
          commit-message: update authors
          title: Update AUTHORS
          body: Credit new contributors by updating AUTHORS
          branch: main
          labels: |
            report
            automated pr
          assignees: WaddahAhmad
          reviewers: WaddahAhmad
          milestone: 1
          draft: false
