name: Bump version
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-tags: 'true'
          fetch-depth: '0'
      - name: Get Tag Name
        id: tag_name
        run: |
          git describe --tags --candidates 1
          git describe --tags --always $(git rev-list --tags --max-count=1)
          echo "::set-output name=tag_name::$(git describe --tags --always $(git rev-list --tags --max-count=1))"
  print_tag_name:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Print Tag Name
        run: |
          echo "Tag Name: ${{ needs.deploy.outputs.tag_name }}"
