name: Bump version
on:
  workflow_dispatch:
    inputs:
      upgrade_level:
        type: choice
        description: kind of update
        default: 'patch'
        options: 
        - patch
        - minor
        - major

jobs:

  bump_tag:
    runs-on: ubuntu-latest
    outputs:
      final_tag: ${{steps.bump_tag.outputs.tag}}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-tags: 'true'
        fetch-depth: '0'
        
    - name: Bump Tag
      id: bump_tag
      shell: bash
      run: make bump_tag
      env:
        upgrade_level: ${{ inputs.upgrade_level }}

  push_tag_name:
    runs-on: ubuntu-latest
    needs: bump_tag
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
      - name: Create version
        run: git tag ${{needs.bump_tag.outputs.final_tag}}
      - name: Commit report
        run: |
          git config --global user.name 'waddah'
          git config --global user.email 'waddah.t.ahmad@gmail.com'
          git push origin ${{needs.bump_tag.outputs.final_tag}}