name: Bump version
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.tag_name.outputs.tag_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-tags: 'true'
          fetch-depth: '0'
      - name: Get Tag Name
        id: tag_name
        run: |
          echo "tag_name=$(git describe --tags --always $(git rev-list --tags --max-count=1))" >> "$GITHUB_OUTPUT"
  print_tag_name:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Print Tag Name
        run: |
          echo "Tag Name: ${{ needs.deploy.outputs.output1 }}"
